name: vpsrun
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
